name: "CodeQL Local Threat Model Configuration"

disable-default-queries: true

queries:
  # Java
  - name: Use Java Local Threat Model queries + extended suite
    uses: GeekMasher/security-queries/java/suites/codeql-java-local.qls@main

  # Python
  - name: Use Python Local Threat Model queries + extended suite
    uses: GeekMasher/security-queries/python/suites/codeql-python-local.qls@main
