name: "GeekMasher CodeQL Configuration"

disable-default-queries: true

packs:
  # > Python
  - geekmasher/codeql-python
  - advanced-security/codeql-python
  - codeql/python-queries:codeql-suites/python-security-extended.qls


paths-ignore:
  # Python
  - vendor/**

  # JavaScript
  - 'node_modules'
  - '**/*.test.js'
