name: "GeekMasher CodeQL Configuration"

packs:
  # C/C++
  - githubsecuritylab/codeql-cpp-queries
  - trailofbits/cpp-queries
  # > C#
  - githubsecuritylab/codeql-csharp-queries
  - githubsecuritylab/codeql-csharp-extensions
  - githubsecuritylab/codeql-csharp-library-sources
  # > Go
  - githubsecuritylab/codeql-go-queries
  - trailofbits/go-queries
  # > Java
  - githubsecuritylab/codeql-java-queries
  - githubsecuritylab/codeql-java-extensions
  - githubsecuritylab/codeql-java-library-sources
  # > JavaScript
  - githubsecuritylab/codeql-javascript-queries
  # > Python
  - geekmasher/codeql-python
  - githubsecuritylab/codeql-python-queries
  # > Ruby
  - githubsecuritylab/codeql-ruby-queries

paths-ignore:
  # Python
  - "vendor/**"
  - "examples/**"
  - "tests/**"

  # JavaScript
  - "node_modules"
  - "**/*.test.js"
