name: Deafult Policy

codescanning:
  level: error
 
dependabot:
  level: moderate

licensing:
  conditions:
    ids:
      - GPL-*
      - LGPL-*
      - AGPL-*

dependencies:
  conditions:
    names:
      - 'npm://gulp-clean-css'

secretscanning:
  level: all
